apiVersion: v1
kind: Service
metadata:
  name: "kimagentdemo"
  namespace: "agents-genaiteam"
spec:
  selector:
    app: "kimagentdemo"
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
